plugins {
    id 'com.android.application'
}

android {
    namespace 'com.prudhviraj.choicevolumelock'
    compileSdk 35

    defaultConfig {
        applicationId 'com.prudhviraj.choicevolumelock'
        minSdk 26
        targetSdk 35
        versionCode 1
        versionName '1.0'
    }

    buildFeatures {
        buildConfig false
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    packaging {
        resources {
            excludes += ['META-INF/LICENSE*', 'META-INF/NOTICE*']
        }
    }
}

dependencies {
    compileOnly 'io.github.libxposed:api:102.0.0'
}
